# =========================
# STAGE 1 : BUILD
# =========================
FROM condaforge/miniforge3:latest AS build

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      git \
      build-essential \
      clang \
 && rm -rf /var/lib/apt/lists/*

ENV IGN_SOCLE_DIR=/usr/local/src/sd-socle

WORKDIR $IGN_SOCLE_DIR

# environnment conda
COPY ./env_conda.yml $IGN_SOCLE_DIR/env_conda.yml
RUN conda update -n base -c conda-forge conda \
 && conda env create -f env_conda.yml

ENV CONDA_PREFIX=/opt/conda/envs/ign-socle
ENV PATH=$CONDA_PREFIX/bin:$PATH

# intallation de GL/gl.sh
RUN conda install -y -c conda-forge libgl-devel=1.7

COPY ./sd-socle $IGN_SOCLE_DIR

ENV IGN_DATA=$IGN_SOCLE_DIR/data

ENV LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$IGN_SOCLE_DIR/lib:$LD_LIBRARY_PATH \
    PATH=$IGN_SOCLE_DIR/bin:$PATH

# construction
ENV CONFIG=Debug
COPY ./build-unix-europe-test.sh .
RUN ./build-unix-europe-test.sh

# =========================
# STAGE 2
# =========================
FROM ubuntu:24.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      gdb \
 && rm -rf /var/lib/apt/lists/*

ENV IGN_SOCLE_DIR=/usr/local/src/sd-socle \
    CONDA_PREFIX=/opt/conda/envs/ign-socle

COPY --from=build $IGN_SOCLE_DIR/include                      $IGN_SOCLE_DIR/include
COPY --from=build $IGN_SOCLE_DIR/extension/cgal/include       $IGN_SOCLE_DIR/extension/cgal/include
COPY --from=build $IGN_SOCLE_DIR/src                          $IGN_SOCLE_DIR/src
COPY --from=build $IGN_SOCLE_DIR/extension/cgal/src           $IGN_SOCLE_DIR/extension/cgal/src
COPY --from=build $IGN_SOCLE_DIR/lib                          $IGN_SOCLE_DIR/lib
COPY --from=build $IGN_SOCLE_DIR/bin                          $IGN_SOCLE_DIR/bin
COPY --from=build $IGN_SOCLE_DIR/data                         $IGN_SOCLE_DIR/data
COPY --from=build $CONDA_PREFIX/include                       $CONDA_PREFIX/include
COPY --from=build $CONDA_PREFIX/lib                           $CONDA_PREFIX/lib
# pour Qt5
COPY --from=build $CONDA_PREFIX/bin                           $CONDA_PREFIX/bin
COPY --from=build $CONDA_PREFIX/mkspecs/linux-g++             $CONDA_PREFIX/mkspecs/linux-g++
COPY --from=build $CONDA_PREFIX/plugins                       $CONDA_PREFIX/plugins

ENV LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$IGN_SOCLE_DIR/lib:$LD_LIBRARY_PATH \
    IGN_DATA=$IGN_SOCLE_DIR/data \
    PATH=$PATH:$IGN_SOCLE_DIR/bin

WORKDIR $IGN_SOCLE_DIR